# List of commands
commandToProcess:

  - displayName: "Home Dir File Count"
    command: "ls -ltr ~| wc -l"
    isScript: false

  - displayName: "Java Processes List"
    command: "/path/to/script1.sh"
    isScript: true

  - displayName: "Random Script"
    command: "/path/to/script2.sh"
    isScript: true

# Make sure the metric prefix ends with a |
metricPrefix: "Custom Metrics|Command Watcher|"

#This will create it in specific Tier. Replace <TIER_ID>
#metricPrefix: "Server|Component:<TIER_ID>|Custom Metrics|Command Watcher|"



